<?php
#===============================================================================
// [summary]
// This is a simple interface designed for making it possible to produce
// html tags and documents using PHP. This interfaces always produces
// systematically indented HTML code to ease the reading and visual debugging
// of HTML documents.
//
// This interface has no external dependencies and can be used by including it
// in a PHP file and creating an instance of the class.
// [usage]
// This is a list of public methods. Please see the README.md for more detailed
// documentation on usage.
//
// 1) $html = new HtmlInterface(); // create a new interface
// 2) ... = new HtmlINterface("html"); // create a new interface with doctype
// 3) $html->doctype("html"); // set the doctype
// 4) $html->indentCharacter(" "); // set indent character as tabs or spaces
// 5) $html->html(); // create a tag !!see README.md for more information
// 6) $html->newline(); //create a newline in HTML document
// 7) $html->comment("comment text"); //create a comment in HTML document
// 8) $html->repeat(HtmlInterface, int); //repeat a fragment n times
#===============================================================================
class HtmlInterface 
{
    //
	const TOP_TAG_NAME = "TOP_TAG_NAME";
	const PROPERTIES = "PROPERTIES";

    
	private $inParseCycle = false;
	private $indentLevel = 0;
	private $indentPattern = "\t"; //change it so that the indent
	//pattern can be changed
	private $selfClosingTagList = array(
		"base", 
		"basefont", 
		"br", 
		"col", 
		"frame", 
		"hr", 
		"input", 
		"link", 
		"meta", 
		"param"
	);

	//something
	private $doctype = "";
	private $topTag = array();
	private $html = "";
	private $childFragments = array();
	
	#-----------------------------------------------------------
	# [summary]
	# Create a new HtmlInterface for use to create HTML.
	# [parameters]
	# 1) The doctype definition of the HTML document to be
	#    created. This is optional. By setting this a doctype
	#    will be added to the document, otherwise the document
	#    will be generated without a doctype.
	# [return]
	# 1) A new HtmlInterface for use.
	#-----------------------------------------------------------
	public function __construct($definition = "")
	{
	    //check if user wants to set a doctype
		if(!empty($definition)) {
		    //user specified a doctype, so set it
			$this->doctype($definition);
		}
	}

    #-----------------------------------------------------------
	# [summary]
	# This is an overload of the PHP __call function. This 
	# passes the name of an HTML tag to be generated along with
	# the attributes to be set to the initializeTag function.
	# [parameters]
	# 1) The name of the tag.
	# 2) Tag properies(attributes, innertext, children/siblings)
	# [return]
	# 1) The tag generated by the initializeTag function.
	#-----------------------------------------------------------
	public function __call($tagName, $properties)
	{
	    //parse the tag properties and generate tag of $tagName
		return $this->html = $this->initializeTag($tagName, $properties);
	}
	
	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	private function initializeTag($tagName, $properties)
	{
		$attributes = array();
		$innerText = "";
		$stringList = array();
		$children = array();
		
		foreach($properties as $property) {
			//since HtmlInterface has a to __toString method
			//this has to be valuated before any
			//string evaluations
			if($property instanceof HtmlInterface) {
				$property->clearDoctype();
				$children[] = $property;
				continue;
			}
			if(strpos($property, "\n") !== false) {
				$children[] = $property;
				continue;
			}
			//inner text and children
			if(is_string($property)) {
				$stringList[] = $property;
				continue;
			}
	    }

	    //
	    $stringCount = count($stringList);
	    if($stringCount % 2) {
			$innerText = $stringList[$stringCount - 1];
	    }
	    
	    for ($nextString = 0; ($nextString + 1) < $stringCount; $nextString += 2) {
	    	$attributes[$stringList[$nextString]] = $stringList[$nextString + 1];
	    }

		return $this->createTag($tagName, $attributes, $innerText, $children);
	}
    
    #-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function parseAttributes($attributes)
	{
		$attributeString = "";
		if(empty($attributes)) {
			return $attributeString;
		}
		foreach ($attributes as $name => $value) {
			$attributeString .= " $name=\"$value\""; // there's a space here
		}
		return $attributeString;
	}

    #-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	private function increaseIndent($childString)
    {	
		$childList = substr_replace(
			$childString,
			"",
			strrpos($childString, "\n")
		);
		$childList = explode("\n", $childList);
		foreach($childList as $index => $child) {
			$childList[$index] = $this->indent() . $child;
		}
		return implode("\n", $childList) . "\n";
		return $childString;
	}
	
	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	//this function is probably going to cause you lots of problems right now...
	// all fixing needs to happen here
	public function parseChildren($children)
	{
		$childString = "";
		$newline = $this->inParseCycle ? "" : "\n";
		if(empty($children)) {
			return $childString;
		}
		if(!is_array($children)) {
			$children = array($children);
		}
		$currentIndentLevel = $this->indentLevel;
		foreach($children as $child) {
			if($child instanceof HtmlInterface) {
				$this->inParseCycle = true;
				$this->indentLevel = 0;
				$child = $this->parseChildren((string)$child);
				$this->indentLevel = $currentIndentLevel;
				$this->inParseCycle = false;
			}
			$child = $this->increaseIndent($child);
			$childString .= $child;
		}
		return $newline . $childString;
	}
    
    #-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function createTag($tagName, $attributes, $innerText = "", $children = "")
	{
		$createdTag = "";
		
		//
		if(in_array($tagName, $this->selfClosingTagList)) {
			//
			if($children) {
				$createdTag = "<$tagName%s>%s%s";
			} else {
				$createdTag = "<$tagName%s>\n%s%s";
			}
			$this->indentLevel = 0;
		} else {
			//
			$createdTag = "<$tagName%s>%s%s</$tagName>\n";
			$this->indentLevel = 1;
		}

		$createdTag = sprintf(
			"$createdTag",
			$this->parseAttributes($attributes),
			$innerText,
			$this->parseChildren($children)
		);
		
		return $createdTag;
	}

    #-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	protected function clearDoctype()
	{
		$this->doctype = "";	
	}
	
	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function doctype($definition) {
		$this->doctype = sprintf(
			"<!DOCTYPE %s>\n",
			$definition
		);
	}
	
	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function repeat(HtmlInterface $html, $count)
	{
		$html->clearDoctype();
		return str_repeat($html, $count);
	}
	
	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function newline() {
		return "\n";
	}
	
	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	private function indent()
	{
		return str_repeat($this->indentPattern, $this->indentLevel);
	}
    
    #-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function __toString()
	{
		return $this->doctype . $this->html;
	}

	#-----------------------------------------------------------
	# [summary]
	# none
	# [parameters]
	# none
	# [return]
	# none
	#-----------------------------------------------------------
	public function comment($comment) {
		return "<!-- $comment -->\n";
	}
}#==================== HtmlInterface end ====================#